---
file:
  spreadsheetId: 1TgHd9EVVOQie4sPOIsPBut6xOd4x1YW9moEfKOaZwZU
  credentialFile: credentials.json
  tabs:
    - name: practitionerRole
      profile: http://hl7.org/fhir/StructureDefinition/PractitionerRole
      resourceType: PractitionerRole
    - name: organisation
      profile: http://hl7.org/fhir/StructureDefinition/Organization
      resourceType: Organization
    - name: practitioner
      profile: http://hl7.org/fhir/StructureDefinition/Practitioner
      resourceType: Practitioner
fhir:
  url: 'http://localhost:8080/fhir'
#  OAuth configuration for fhir client
#  oauth:
#    url: http://loclhost:8081/auth/realms/clin/protocol/openid-connect/token
#    client_id: client
#    client_secret: secret

