---
file:
  spreadsheetId: 1TgHd9EVVOQie4sPOIsPBut6xOd4x1YW9moEfKOaZwZU
  credentialFile: credentials.json
  tabs:
    - name: practitionerRole
      profile: http://hl7.org/fhir/StructureDefinition/PractitionerRole
      resourceType: PractitionerRole
    - name: organisation
      profile: http://hl7.org/fhir/StructureDefinition/Organization
      resourceType: Organization
fhir:
  url: 'http://localhost:8080/fhir'

