---
file:
  spreadsheetId: 1TgHd9EVVOQie4sPOIsPBut6xOd4x1YW9moEfKOaZwZU
  credentialFile: creds/credentials.json
  tabs:
    - name: practitionerRole
      profile: http://hl7.org/fhir/StructureDefinition/PractitionerRole
      resourceType: PractitionerRole
    - name: organisation
      profile: http://hl7.org/fhir/StructureDefinition/Organization
      resourceType: Organization
    - name: practitioner
      profile: http://hl7.org/fhir/StructureDefinition/Practitioner
      resourceType: Practitioner
    - name: patient
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-patient
      resourceType: Patient
    - name: serviceRequest
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-service-request
      resourceType: ServiceRequest
    - name: FMH
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-fmh
      resourceType: FamilyMemberHistory
    - name: clinicalImpression
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-clinical-impression
      resourceType: ClinicalImpression
    - name: observation_CGH
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-observation
      resourceType: Observation
    - name: observation_INDIC_INVES
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-observation
      resourceType: Observation
    - name: observation_ETH_PHENO
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-observation
      resourceType: Observation
    - name: observation_CONS
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-observation
      resourceType: Observation
    - name: group
      profile: http://fhir.cqgc.ferlab.bio/StructureDefinition/cqgc-family-group
      resourceType: Group
fhir:
  url: 'http://localhost:8080/fhir'
#  OAuth configuration for fhir client
#  oauth:
#    url: http://loclhost:8081/auth/realms/clin/protocol/openid-connect/token
#    client_id: client
#    client_secret: secret

