name: Build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Install dev deps
        run: pip install -r requirements-dev.txt
      - name: Run Test
        run: python -m pytest